testname: Missing fundamental test
testId: missing_fund_test1
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: The purpose of this test is to compare different audio clips to determine which has the best bass response.      
    - type: mushra
      id: trial_1
      name: MUSHRA
      content: Listen to the Cond sounds and compare them with the reference, then give them a score with the slider below. Only the slider for the sound you're currently playing can be moved. When you feel like you're done, press Next.
      enableLooping: true 
      reference: configs/resources/audio/ref_nofilter.wav
      createAnchor35: false
      createAnchor70: false
      stimuli:
          C1: configs/resources/audio/concave2.wav
          C2: configs/resources/audio/down_exp5.wav
          C3: configs/resources/audio/down_exp10.wav
          C4: configs/resources/audio/erb_based_harmonic50hz_exp5end.wav
          C5: configs/resources/audio/known_nld.wav
          C6: configs/resources/audio/ref_filter.wav
    - 
          # - random
          - type: mushra
            id: trial_2
            name: MUSHRA - 2
            content: 
            enableLooping: true 
            reference: configs/resources/audio/ref_nofilter.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
              C1: configs/resources/audio/concave2.wav
              C2: configs/resources/audio/down_exp5.wav
              C3: configs/resources/audio/down_exp10.wav
              C4: configs/resources/audio/erb_based_harmonic50hz_exp5end.wav
              C5: configs/resources/audio/known_nld.wav
              C6: configs/resources/audio/ref_filter.wav
          - type: mushra
            id: trial_3
            name: MUSHRA - 3
            content: 
            enableLooping: true 
            reference: configs/resources/audio/ref_nofilter.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/concave2.wav
                C2: configs/resources/audio/down_exp5.wav
                C3: configs/resources/audio/down_exp10.wav
                C4: configs/resources/audio/erb_based_harmonic50hz_exp5end.wav
                C5: configs/resources/audio/known_nld.wav
                C6: configs/resources/audio/ref_filter.wav
          - type: mushra
            id: trial_4
            name: MUSHRA - 4
            content: 
            enableLooping: true 
            reference: configs/resources/audio/ref_nofilter.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/concave2.wav
                C2: configs/resources/audio/down_exp5.wav
                C3: configs/resources/audio/down_exp10.wav
                C4: configs/resources/audio/erb_based_harmonic50hz_exp5end.wav
                C5: configs/resources/audio/known_nld.wav
                C6: configs/resources/audio/ref_filter.wav     
          - type: mushra
            id: trial_5
            name: MUSHRA - 5
            content: 
            enableLooping: true 
            reference: configs/resources/audio/ref_nofilter.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/concave2.wav
                C2: configs/resources/audio/down_exp5.wav
                C3: configs/resources/audio/down_exp10.wav
                C4: configs/resources/audio/erb_based_harmonic50hz_exp5end.wav
                C5: configs/resources/audio/known_nld.wav
                C6: configs/resources/audio/ref_filter.wav         
    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: Full name 
            name: name
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          # - type: likert
          #   name: gender
          #   label: Gender
          #   response:
          #    - value: female
          #      label: Female
          #    - value: male
          #      label: Male
          #    - value: other
          #      label: Other
